name: mobilebamking
description: Kumakan - Mobile Banking
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Réseau
  http: ^1.2.2

  # État
  provider: ^6.1.2

  # Stockage local
  shared_preferences: ^2.3.2

  # Firebase (Stratégie B)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

  # Vocaux
  sherpa_onnx: ^1.13.4
  serious_python: ^0.9.0
  record: ^6.0.0
  audioplayers: ^6.1.0
  flutter_tts: ^4.2.5

  # Utils
  path_provider: ^2.1.4
  path: ^1.9.0
  crypto: ^3.0.5
  ffi: ^2.1.3
  uuid: ^4.5.1

  # Polices Google
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/vits/
    - app/app.zip